<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.1" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Features\Class\EditClass\" />
    <Folder Include="Features\Class\CreateClassSession\" />
    <Folder Include="Features\User\Commands\EditUser\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JMMinistry.Common\JMMinistry.Common.csproj" />
    <ProjectReference Include="..\JMMinistry.Domain\JMMinistry.Domain.csproj" />
    <ProjectReference Include="..\JMMinistry.Infrastructure.Persistence\JMMinistry.Infrastructure.Persistence.csproj" />
  </ItemGroup>

</Project>
