<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Features\Classes\EditClass\" />
    <Folder Include="Features\Classes\CreateClassSession\" />
    <Folder Include="Features\Meetings\Commands\RegisterAttendance\" />
    <Folder Include="Features\User\Commands\EditUser\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JMMinistry.Common\JMMinistry.Common.csproj" />
    <ProjectReference Include="..\JMMinistry.Domain\JMMinistry.Domain.csproj" />
  </ItemGroup>

</Project>
