# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


pool:
  name: Default
  demands: 
  - Agent.Name -equals Raspberry

steps:  
- task: CmdLine@2
  displayName: 'Stop containers'
  inputs:
    script: 'docker compose down'
    workingDirectory: '/home/src/JMMinistry'

- task: CmdLine@2
  displayName: 'Update repo'
  inputs:
    script: 'git fetch && git pull'
    workingDirectory: '/home/src/JMMinistry'

- task: CmdLine@2
  displayName: 'Build and run containers'
  inputs:
    script: 'docker compose up -d --build'
    workingDirectory: '/home/src/JMMinistry'




