# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


pool:
  name: Default
  demands: 
  - Agent.Name -equals DietPiAgent


steps:  
- task: CmdLine@2
  displayName: 'Clean Docker if disk usage above 50%'
  inputs:
    script: |
      USAGE=$(df / | awk 'NR==2 {gsub("%",""); print $5}')
      echo "Current disk usage: ${USAGE}%"
      if [ "$USAGE" -ge 50 ]; then
        echo "Disk usage is ${USAGE}%, running docker system prune..."
        docker system prune -af --volumes
      else
        echo "Disk usage is ${USAGE}%, no cleanup needed."
      fi

- task: CmdLine@2
  displayName: 'Stop containers'
  inputs:
    script: 'docker compose down'
    
- task: CmdLine@2
  displayName: 'Configure frontend network'
  inputs:
    script: |
      NETWORK_NAME="jm-frontend"
      
      # Check if the network exists
      docker network inspect "$NETWORK_NAME" >/dev/null 2>&1 || \
          docker network create --driver bridge "$NETWORK_NAME"

- task: CmdLine@2
  displayName: 'Configure backend network'
  inputs:
    script: |
      NETWORK_NAME="jm-backend"
      
      # Check if the network exists
      docker network inspect "$NETWORK_NAME" >/dev/null 2>&1 || \
          docker network create --driver bridge "$NETWORK_NAME"

- task: CmdLine@2
  displayName: 'Configure db network'
  inputs:
    script: |
      NETWORK_NAME="jm-db"
      
      # Check if the network exists
      docker network inspect "$NETWORK_NAME" >/dev/null 2>&1 || \
          docker network create --driver bridge "$NETWORK_NAME"

- task: CmdLine@2
  displayName: 'Build and run containers'
  inputs:
    script: |
      export DefaultUser__Document=$(DefaultUser__Document)
      export DefaultUser__LastName=$(DefaultUser__LastName)
      export DefaultUser__Name=$(DefaultUser__Name)
      export DefaultUser__Password=$(DefaultUser__Password)
      export JwtSettings__Audience=$(JwtSettings__Audience)
      export JwtSettings__DurationInMinutes=$(JwtSettings__DurationInMinutes)
      export JwtSettings__Issuer=$(JwtSettings__Issuer)
      export JwtSettings__Key=$(JwtSettings__Key)
      export POSTGRES_PASSWORD=$(POSTGRES_PASSWORD)
      export API_URL=$(SERVER_HOST)
      docker compose build --no-cache
      docker compose up -d




