version: '3.9'

networks:
  jm-backend:
    external: true
    #driver: bridge
  jm-frontend:
    external: true
    #driver: bridge
  jm-db:
    external: true
    #driver: bridge

services:
    database:
        # Official Postgres image from DockerHub (we use the last version)
        image: 'postgres:latest'

        # By default, a Postgres database is running on the 5432 port.
        # If we want to access the database from our computer (outside the container),
        # we must share the port with our computer's port.
        # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
        # Note: You are free to change your computer's port,
        # but take into consideration that it will change the way
        # you are connecting to your database.
        ports:
            - 5432:5432

        environment:
            - POSTGRES_USER=jm-db # The PostgreSQL user (useful to connect to the database)
            - POSTGRES_PASSWORD # The PostgreSQL password (useful to connect to the database)
            - POSTGRES_DB=jm-db # The PostgreSQL default database (automatically created at first launch)

        volumes:
            # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path
            # It means that every time the repository is modifying the data inside
            # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`
            # You don't need to create the `db-data` folder. Docker Compose will do it for you
            - /app-data/db/:/var/lib/postgresql/data/
        networks:
            - jm-db

    jmministry.api:
        #image: ${DOCKER_REGISTRY-}jmministryapi
        container_name: jmministry-api
        build:
            context: .
            dockerfile: JMMinistry.API/Dockerfile
        environment:
            - ASPNETCORE_HTTP_PORTS=8080
            - JwtSettings__Key
            - JwtSettings__Issuer
            - JwtSettings__DurationInMinutes
            - JwtSettings__Audience
            - DefaultUser__Password
            - DefaultUser__Name
            - DefaultUser__LastName
            - DefaultUser__Document
        ports:
            - 62421:8080
        networks:
            - jm-backend
            - jm-db
            - jm-frontend 
        depends_on:
            - database

    jmministry.web:
       container_name: jmministry-web
       build:
           context: .
           dockerfile: JMMinistry.Web/Dockerfile
           args:
            - API_URL=$API_URL
       environment:
            - API_URL
       ports:
           - 62422:80
       networks:
           - jm-frontend
       depends_on:
           - jmministry.api