version: "3.9"

networks:
  jm-backend:
    external: true
  jm-frontend:
    external: true
  jm-db:
    external: true

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    command: start --user root --pass root --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./app-data/db/surrealdb-data:/mydata
    healthcheck:
      test: ["CMD", "/surreal", "is-ready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - jm-db

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - 9005:9000
      - 9006:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./app-data/minio-data:/data
    networks:
      - jm-db

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80 # Dashboard UI accessible at http://localhost:8081
      - 5341:5341 # Standard port for OTLP gRPC/HTTP ingestion
    volumes:
      - ./app-data/seq-data:/data
    networks:
      - jm-backend

  jmministry.api:
    #image: ${DOCKER_REGISTRY-}jmministryapi
    container_name: jmministry-api
    build:
      context: .
      dockerfile: backend/JMMinistry.API/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - JwtSettings__Key
      - JwtSettings__Issuer
      - JwtSettings__DurationInMinutes
      - JwtSettings__Audience
      - DefaultUser__Password
      - DefaultUser__Name
      - DefaultUser__LastName
      - DefaultUser__Document
      - OTEL_SERVICE_NAME=jmministry-api
      # Tell the .NET OpenTelemetry exporter to send data to Seq
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://seq:5341
    ports:
      - 62421:8080
    networks:
      - jm-backend
      - jm-db
      - jm-frontend
    depends_on:
      surrealdb:
        condition: service_healthy
