//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMMinistry.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMMinistry.Common.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned.
        /// </summary>
        public static string Abandoned {
            get {
                return ResourceManager.GetString("Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Cycles.
        /// </summary>
        public static string ActiveCycles {
            get {
                return ResourceManager.GetString("ActiveCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add disciples.
        /// </summary>
        public static string AddDisciples {
            get {
                return ResourceManager.GetString("AddDisciples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add disciples to cell.
        /// </summary>
        public static string AddDisciplesAction {
            get {
                return ResourceManager.GetString("AddDisciplesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address information.
        /// </summary>
        public static string AddressInformation {
            get {
                return ResourceManager.GetString("AddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Session.
        /// </summary>
        public static string AddSession {
            get {
                return ResourceManager.GetString("AddSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Staff.
        /// </summary>
        public static string AddStaff {
            get {
                return ResourceManager.GetString("AddStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add step completion.
        /// </summary>
        public static string AddStepCompletion {
            get {
                return ResourceManager.GetString("AddStepCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub-Step.
        /// </summary>
        public static string AddSubStep {
            get {
                return ResourceManager.GetString("AddSubStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to {0} this {1}: {2}?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Guide.
        /// </summary>
        public static string AssignGuide {
            get {
                return ResourceManager.GetString("AssignGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance {0}.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendances.
        /// </summary>
        public static string Attendances {
            get {
                return ResourceManager.GetString("Attendances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees: {0}.
        /// </summary>
        public static string Attendees {
            get {
                return ResourceManager.GetString("Attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed, verify your credentials.
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessful Authentication.
        /// </summary>
        public static string AuthenticationSucess {
            get {
                return ResourceManager.GetString("AuthenticationSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fellow servants.
        /// </summary>
        public static string CellMates {
            get {
                return ResourceManager.GetString("CellMates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells.
        /// </summary>
        public static string Cells {
            get {
                return ResourceManager.GetString("Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change photo.
        /// </summary>
        public static string ChangePhoto {
            get {
                return ResourceManager.GetString("ChangePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string CheckDocument {
            get {
                return ResourceManager.GetString("CheckDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Cycle.
        /// </summary>
        public static string CloseCycle {
            get {
                return ResourceManager.GetString("CloseCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete step for disciples.
        /// </summary>
        public static string CompleteStepForDisciplesAction {
            get {
                return ResourceManager.GetString("CompleteStepForDisciplesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion date.
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidate.
        /// </summary>
        public static string Consolidate {
            get {
                return ResourceManager.GetString("Consolidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.
        /// </summary>
        public static string Coordinator {
            get {
                return ResourceManager.GetString("Coordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create new cell.
        /// </summary>
        public static string CreateCellAction {
            get {
                return ResourceManager.GetString("CreateCellAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Cycle.
        /// </summary>
        public static string CreateCycle {
            get {
                return ResourceManager.GetString("CreateCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create disciple step.
        /// </summary>
        public static string CreateDiscipleStepAction {
            get {
                return ResourceManager.GetString("CreateDiscipleStepAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new {0}.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string CycleAttendance {
            get {
                return ResourceManager.GetString("CycleAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Closed.
        /// </summary>
        public static string CycleClosed {
            get {
                return ResourceManager.GetString("CycleClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles.
        /// </summary>
        public static string Cycles {
            get {
                return ResourceManager.GetString("Cycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline Passed.
        /// </summary>
        public static string DeadlinePassed {
            get {
                return ResourceManager.GetString("DeadlinePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete disciple step.
        /// </summary>
        public static string DeleteDiscipleStepAction {
            get {
                return ResourceManager.GetString("DeleteDiscipleStepAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciple.
        /// </summary>
        public static string Disciple {
            get {
                return ResourceManager.GetString("Disciple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciples.
        /// </summary>
        public static string Disciples {
            get {
                return ResourceManager.GetString("Disciples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipleship Journal.
        /// </summary>
        public static string DiscipleshipJournal {
            get {
                return ResourceManager.GetString("DiscipleshipJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disciple step.
        /// </summary>
        public static string DiscipleStep {
            get {
                return ResourceManager.GetString("DiscipleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciple Steps.
        /// </summary>
        public static string DiscipleSteps {
            get {
                return ResourceManager.GetString("DiscipleSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cycle.
        /// </summary>
        public static string EditCycle {
            get {
                return ResourceManager.GetString("EditCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string EditEntity {
            get {
                return ResourceManager.GetString("EditEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Step.
        /// </summary>
        public static string EditStep {
            get {
                return ResourceManager.GetString("EditStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll Disciples.
        /// </summary>
        public static string EnrollDisciples {
            get {
                return ResourceManager.GetString("EnrollDisciples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrolled.
        /// </summary>
        public static string Enrolled {
            get {
                return ResourceManager.GetString("Enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Deadline.
        /// </summary>
        public static string EnrollmentDeadline {
            get {
                return ResourceManager.GetString("EnrollmentDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollments.
        /// </summary>
        public static string Enrollments {
            get {
                return ResourceManager.GetString("Enrollments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unknown error trying to retrieve the resource.
        /// </summary>
        public static string ErrorFetching {
            get {
                return ResourceManager.GetString("ErrorFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to {0}.
        /// </summary>
        public static string FailedTo {
            get {
                return ResourceManager.GetString("FailedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load resource.
        /// </summary>
        public static string FailedToLoadResource {
            get {
                return ResourceManager.GetString("FailedToLoadResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch cell details.
        /// </summary>
        public static string FetchCellAction {
            get {
                return ResourceManager.GetString("FetchCellAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch the cells in your ministry.
        /// </summary>
        public static string FetchCellsAction {
            get {
                return ResourceManager.GetString("FetchCellsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch disciples in cell.
        /// </summary>
        public static string FetchDisciplesAction {
            get {
                return ResourceManager.GetString("FetchDisciplesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch disciple steps.
        /// </summary>
        public static string FetchDiscipleStepsAction {
            get {
                return ResourceManager.GetString("FetchDiscipleStepsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch eligible disciples.
        /// </summary>
        public static string FetchEligibleDisciplesAction {
            get {
                return ResourceManager.GetString("FetchEligibleDisciplesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch disciples for this step.
        /// </summary>
        public static string FetchStepDisciplesAction {
            get {
                return ResourceManager.GetString("FetchStepDisciplesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        public static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gained.
        /// </summary>
        public static string Gained {
            get {
                return ResourceManager.GetString("Gained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gained person.
        /// </summary>
        public static string GainedPerson {
            get {
                return ResourceManager.GetString("GainedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gained Users.
        /// </summary>
        public static string GainedUsers {
            get {
                return ResourceManager.GetString("GainedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        public static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import users.
        /// </summary>
        public static string ImportUsers {
            get {
                return ResourceManager.GetString("ImportUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a cell.
        /// </summary>
        public static string InACell {
            get {
                return ResourceManager.GetString("InACell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Status.
        /// </summary>
        public static string InitialStatus {
            get {
                return ResourceManager.GetString("InitialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Prayers.
        /// </summary>
        public static string InPrayers {
            get {
                return ResourceManager.GetString("InPrayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Cycles.
        /// </summary>
        public static string ManageCycles {
            get {
                return ResourceManager.GetString("ManageCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Abandoned.
        /// </summary>
        public static string MarkAbandoned {
            get {
                return ResourceManager.GetString("MarkAbandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Abandoned.
        /// </summary>
        public static string MarkAbandoned2 {
            get {
                return ResourceManager.GetString("MarkAbandoned2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Completed.
        /// </summary>
        public static string MarkCompleted {
            get {
                return ResourceManager.GetString("MarkCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} have been married successfully..
        /// </summary>
        public static string MarriedSuccessfully {
            get {
                return ResourceManager.GetString("MarriedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marry.
        /// </summary>
        public static string Marry {
            get {
                return ResourceManager.GetString("Marry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} will be registered as married..
        /// </summary>
        public static string MarryConfirmation {
            get {
                return ResourceManager.GetString("MarryConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Attendance.
        /// </summary>
        public static string MinAttendance {
            get {
                return ResourceManager.GetString("MinAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing: {0}.
        /// </summary>
        public static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ministry.
        /// </summary>
        public static string MyMinistry {
            get {
                return ResourceManager.GetString("MyMinistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Cells registered, please create one..
        /// </summary>
        public static string NoCells {
            get {
                return ResourceManager.GetString("NoCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cycles available.
        /// </summary>
        public static string NoCycles {
            get {
                return ResourceManager.GetString("NoCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No disciples registered for this step yet..
        /// </summary>
        public static string NoDisciples {
            get {
                return ResourceManager.GetString("NoDisciples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No eligible disciples found for this step..
        /// </summary>
        public static string NoEligibleDisciples {
            get {
                return ResourceManager.GetString("NoEligibleDisciples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No enrollments.
        /// </summary>
        public static string NoEnrollments {
            get {
                return ResourceManager.GetString("NoEnrollments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requirements.
        /// </summary>
        public static string NoRequirements {
            get {
                return ResourceManager.GetString("NoRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sessions.
        /// </summary>
        public static string NoSessions {
            get {
                return ResourceManager.GetString("NoSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No staff assigned.
        /// </summary>
        public static string NoStaff {
            get {
                return ResourceManager.GetString("NoStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening date.
        /// </summary>
        public static string OpeningDate {
            get {
                return ResourceManager.GetString("OpeningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Step.
        /// </summary>
        public static string ParentStep {
            get {
                return ResourceManager.GetString("ParentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition.
        /// </summary>
        public static string Petition {
            get {
                return ResourceManager.GetString("Petition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Attendance.
        /// </summary>
        public static string RecordAttendance {
            get {
                return ResourceManager.GetString("RecordAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a cell.
        /// </summary>
        public static string RegisterCell {
            get {
                return ResourceManager.GetString("RegisterCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove disciple from cell.
        /// </summary>
        public static string RemoveDiscipleAction {
            get {
                return ResourceManager.GetString("RemoveDiscipleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires admin approval.
        /// </summary>
        public static string RequiresAdminApproval {
            get {
                return ResourceManager.GetString("RequiresAdminApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Cycle.
        /// </summary>
        public static string RequiresCycle {
            get {
                return ResourceManager.GetString("RequiresCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling cycles prevents adding sub-steps to this step..
        /// </summary>
        public static string RequiresCycleWarning {
            get {
                return ResourceManager.GetString("RequiresCycleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        public static string Resolved {
            get {
                return ResourceManager.GetString("Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        public static string Schools {
            get {
                return ResourceManager.GetString("Schools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option.
        /// </summary>
        public static string SelectAnOption {
            get {
                return ResourceManager.GetString("SelectAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your desired language.
        /// </summary>
        public static string SelectCulture {
            get {
                return ResourceManager.GetString("SelectCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cycle.
        /// </summary>
        public static string SelectCycle {
            get {
                return ResourceManager.GetString("SelectCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select day.
        /// </summary>
        public static string SelectDay {
            get {
                return ResourceManager.GetString("SelectDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select photo.
        /// </summary>
        public static string SelectPhoto {
            get {
                return ResourceManager.GetString("SelectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in our server, please contact the administrator to report the issue.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session expired, please log in again.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Steps.
        /// </summary>
        public static string SubSteps {
            get {
                return ResourceManager.GetString("SubSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timothy.
        /// </summary>
        public static string Timothy {
            get {
                return ResourceManager.GetString("Timothy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under revision.
        /// </summary>
        public static string UnderRevision {
            get {
                return ResourceManager.GetString("UnderRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update cell.
        /// </summary>
        public static string UpdateCellAction {
            get {
                return ResourceManager.GetString("UpdateCellAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update disciple step.
        /// </summary>
        public static string UpdateDiscipleStepAction {
            get {
                return ResourceManager.GetString("UpdateDiscipleStepAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update step status.
        /// </summary>
        public static string UpdateStepCompletionAction {
            get {
                return ResourceManager.GetString("UpdateStepCompletionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} already exists without a cell. Add as disciple?.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} already belongs to a cell.
        /// </summary>
        public static string UserHasCell {
            get {
                return ResourceManager.GetString("UserHasCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Verify your input.
        /// </summary>
        public static string VerifyYourInputs {
            get {
                return ResourceManager.GetString("VerifyYourInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without cell.
        /// </summary>
        public static string WithoutCell {
            get {
                return ResourceManager.GetString("WithoutCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years old.
        /// </summary>
        public static string YearsOld {
            get {
                return ResourceManager.GetString("YearsOld", resourceCulture);
            }
        }
    }
}
