// <auto-generated />
using System;
using JMMinistry.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JMMinistry.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(JmDbContext))]
    [Migration("20240603004554_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "meeting_type", new[] { "one", "rocks", "family" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "member_type", new[] { "coordinator", "staff", "asistant" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ministry_status", new[] { "guess", "gained", "consolidating", "disciple", "leader" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CellAttendancePersonalInfo", b =>
                {
                    b.Property<string>("AttendeesDocument")
                        .HasColumnType("text");

                    b.Property<int>("CellAttendancesId")
                        .HasColumnType("integer");

                    b.HasKey("AttendeesDocument", "CellAttendancesId");

                    b.HasIndex("CellAttendancesId");

                    b.ToTable("CellAttendancePersonalInfo");
                });

            modelBuilder.Entity("ClassAttendancePersonalInfo", b =>
                {
                    b.Property<string>("AttendeesDocument")
                        .HasColumnType("text");

                    b.Property<int>("ClassAttendancesId")
                        .HasColumnType("integer");

                    b.HasKey("AttendeesDocument", "ClassAttendancesId");

                    b.HasIndex("ClassAttendancesId");

                    b.ToTable("ClassAttendancePersonalInfo");
                });

            modelBuilder.Entity("JMMinistry.Domain.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("JMMinistry.Domain.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateRecorded")
                        .HasColumnType("date");

                    b.Property<decimal>("Grade")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<string>("Student")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("JMMinistry.Domain.Cell", b =>
                {
                    b.Property<int>("CellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CellId"));

                    b.Property<string>("LeaderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MainCell")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("CellId");

                    b.HasIndex("LeaderId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("JMMinistry.Domain.CellAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CellId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.ToTable("CellAttendance");
                });

            modelBuilder.Entity("JMMinistry.Domain.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<int>("ClassNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("JMMinistry.Domain.ClassAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateRecorded")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassAttendances");
                });

            modelBuilder.Entity("JMMinistry.Domain.ClassStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Debt")
                        .HasColumnType("numeric");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassStudents");
                });

            modelBuilder.Entity("JMMinistry.Domain.Convention", b =>
                {
                    b.Property<int>("ConventionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConventionId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("MinistryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ConventionId");

                    b.HasIndex("MinistryId");

                    b.ToTable("Conventions");
                });

            modelBuilder.Entity("JMMinistry.Domain.ConventionAttendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("ConventionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Debt")
                        .HasColumnType("numeric");

                    b.Property<string>("InvitedById")
                        .HasColumnType("text");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("ConventionId");

                    b.HasIndex("InvitedById");

                    b.ToTable("ConventionAttendees");
                });

            modelBuilder.Entity("JMMinistry.Domain.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("MinistryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MinistryId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("JMMinistry.Domain.Gained", b =>
                {
                    b.Property<int>("GainedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GainedId"));

                    b.Property<bool>("Contacted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("InACell")
                        .HasColumnType("boolean");

                    b.Property<string>("InvitedById")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GainedId");

                    b.HasIndex("InvitedById");

                    b.ToTable("Gaineds");
                });

            modelBuilder.Entity("JMMinistry.Domain.MeetingAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MeetingType")
                        .HasColumnType("integer");

                    b.Property<string>("PersonId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("MeetingAttendances");
                });

            modelBuilder.Entity("JMMinistry.Domain.Ministry", b =>
                {
                    b.Property<int>("MinistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MinistryId"));

                    b.Property<string>("MinistryManagementId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MinistryId");

                    b.ToTable("Ministries");
                });

            modelBuilder.Entity("JMMinistry.Domain.MinistryManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MemberType")
                        .HasColumnType("integer");

                    b.Property<int>("MinistryId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MinistryId");

                    b.ToTable("MinistryManagements");
                });

            modelBuilder.Entity("JMMinistry.Domain.PersonalInfo", b =>
                {
                    b.Property<string>("Document")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<int?>("CellId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GainedId")
                        .HasColumnType("integer");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Document");

                    b.HasIndex("CellId");

                    b.HasIndex("GainedId")
                        .IsUnique();

                    b.ToTable("PersonalInfos");
                });

            modelBuilder.Entity("JMMinistry.Domain.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("CellAttendancePersonalInfo", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", null)
                        .WithMany()
                        .HasForeignKey("AttendeesDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.CellAttendance", null)
                        .WithMany()
                        .HasForeignKey("CellAttendancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassAttendancePersonalInfo", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", null)
                        .WithMany()
                        .HasForeignKey("AttendeesDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.ClassAttendance", null)
                        .WithMany()
                        .HasForeignKey("ClassAttendancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JMMinistry.Domain.Assignment", b =>
                {
                    b.HasOne("JMMinistry.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("JMMinistry.Domain.Cell", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Leader")
                        .WithMany("Cells")
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("JMMinistry.Domain.CellAttendance", b =>
                {
                    b.HasOne("JMMinistry.Domain.Cell", "Cell")
                        .WithMany()
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cell");
                });

            modelBuilder.Entity("JMMinistry.Domain.Class", b =>
                {
                    b.HasOne("JMMinistry.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("JMMinistry.Domain.ClassAttendance", b =>
                {
                    b.HasOne("JMMinistry.Domain.Class", "Class")
                        .WithMany("ClassAttendances")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("JMMinistry.Domain.ClassStudent", b =>
                {
                    b.HasOne("JMMinistry.Domain.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Student")
                        .WithMany("Classes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JMMinistry.Domain.Convention", b =>
                {
                    b.HasOne("JMMinistry.Domain.Ministry", "Ministry")
                        .WithMany()
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ministry");
                });

            modelBuilder.Entity("JMMinistry.Domain.ConventionAttendee", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Attendee")
                        .WithMany("Conventions")
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.Convention", "Convention")
                        .WithMany()
                        .HasForeignKey("ConventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.PersonalInfo", "InvitedBy")
                        .WithMany("ConventionInvites")
                        .HasForeignKey("InvitedById");

                    b.Navigation("Attendee");

                    b.Navigation("Convention");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("JMMinistry.Domain.Event", b =>
                {
                    b.HasOne("JMMinistry.Domain.Ministry", "Ministry")
                        .WithMany()
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ministry");
                });

            modelBuilder.Entity("JMMinistry.Domain.Gained", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", "InvitedBy")
                        .WithMany("Gained")
                        .HasForeignKey("InvitedById");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("JMMinistry.Domain.MeetingAttendance", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Person")
                        .WithMany("MeetingAttendances")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("JMMinistry.Domain.MinistryManagement", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Member")
                        .WithMany("MinistryManagements")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.Ministry", "Ministry")
                        .WithMany("MinistryManagements")
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Ministry");
                });

            modelBuilder.Entity("JMMinistry.Domain.PersonalInfo", b =>
                {
                    b.HasOne("JMMinistry.Domain.Cell", "Cell")
                        .WithMany("Disciples")
                        .HasForeignKey("CellId");

                    b.HasOne("JMMinistry.Domain.Gained", "GainedRecord")
                        .WithOne("Person")
                        .HasForeignKey("JMMinistry.Domain.PersonalInfo", "GainedId");

                    b.Navigation("Cell");

                    b.Navigation("GainedRecord");
                });

            modelBuilder.Entity("JMMinistry.Domain.Cell", b =>
                {
                    b.Navigation("Disciples");
                });

            modelBuilder.Entity("JMMinistry.Domain.Class", b =>
                {
                    b.Navigation("ClassAttendances");
                });

            modelBuilder.Entity("JMMinistry.Domain.Gained", b =>
                {
                    b.Navigation("Person")
                        .IsRequired();
                });

            modelBuilder.Entity("JMMinistry.Domain.Ministry", b =>
                {
                    b.Navigation("MinistryManagements");
                });

            modelBuilder.Entity("JMMinistry.Domain.PersonalInfo", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("Classes");

                    b.Navigation("ConventionInvites");

                    b.Navigation("Conventions");

                    b.Navigation("Gained");

                    b.Navigation("MeetingAttendances");

                    b.Navigation("MinistryManagements");
                });
#pragma warning restore 612, 618
        }
    }
}
