<Project Sdk="Aspire.AppHost.Sdk/13.1.1">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>77b1bc47-13d1-4cf2-bf2b-61fa5fb3db30</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JMMinistry.API\JMMinistry.API.csproj" />
    <ProjectReference Include="..\JMMinistry.Web\JMMinistry.Web.csproj" />
  </ItemGroup>

</Project>
