// <auto-generated />
using System;
using JMMinistry.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JMMinistry.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JmDbContext))]
    [Migration("20260313184720_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "meeting_type", new[] { "one", "rocks", "family" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "member_type", new[] { "coordinator", "staff", "assistant" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ministry_status", new[] { "guess", "gained", "consolidating", "disciple", "leader" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CellAttendancePersonalInfo", b =>
                {
                    b.Property<string>("AttendeesId")
                        .HasColumnType("text");

                    b.Property<int>("CellAttendancesId")
                        .HasColumnType("integer");

                    b.HasKey("AttendeesId", "CellAttendancesId");

                    b.HasIndex("CellAttendancesId");

                    b.ToTable("CellAttendancePersonalInfo");
                });

            modelBuilder.Entity("CellPersonalInfo", b =>
                {
                    b.Property<int>("CellsId")
                        .HasColumnType("integer");

                    b.Property<string>("LeadersId")
                        .HasColumnType("text");

                    b.HasKey("CellsId", "LeadersId");

                    b.HasIndex("LeadersId");

                    b.ToTable("CellPersonalInfo");
                });

            modelBuilder.Entity("DiscipleStepDiscipleStep", b =>
                {
                    b.Property<int>("DiscipleStepId")
                        .HasColumnType("integer");

                    b.Property<int>("DiscipleStepRequirementsId")
                        .HasColumnType("integer");

                    b.HasKey("DiscipleStepId", "DiscipleStepRequirementsId");

                    b.HasIndex("DiscipleStepRequirementsId");

                    b.ToTable("DiscipleStepRequirement", (string)null);
                });

            modelBuilder.Entity("JMMinistry.Domain.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("JMMinistry.Domain.Cell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<int?>("Day")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("LocalityId")
                        .HasColumnType("integer");

                    b.Property<bool>("MainCell")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("OpeningDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("LocalityId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("JMMinistry.Domain.CellAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CellId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.ToTable("CellAttendances");
                });

            modelBuilder.Entity("JMMinistry.Domain.Convention", b =>
                {
                    b.Property<int>("ConventionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConventionId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ConventionId");

                    b.ToTable("Conventions");
                });

            modelBuilder.Entity("JMMinistry.Domain.ConventionAttendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("ConventionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Debt")
                        .HasColumnType("numeric");

                    b.Property<string>("InvitedById")
                        .HasColumnType("text");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("ConventionId");

                    b.HasIndex("InvitedById");

                    b.ToTable("ConventionAttendees");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.CycleAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CycleSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("DiscipleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscipleId");

                    b.HasIndex("CycleSessionId", "DiscipleId")
                        .IsUnique();

                    b.ToTable("CycleAttendances");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.CycleEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CycleStaffId")
                        .HasColumnType("integer");

                    b.Property<string>("DiscipleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EnrolledAt")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepCycleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CycleStaffId");

                    b.HasIndex("DiscipleId");

                    b.HasIndex("StepCycleId", "DiscipleId")
                        .IsUnique();

                    b.ToTable("CycleEnrollments");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.CycleSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("StepCycleId")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StepCycleId");

                    b.ToTable("CycleSessions");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.CycleStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("StepCycleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("StepCycleId", "PersonId")
                        .IsUnique();

                    b.ToTable("CycleStaff");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.DiscipleStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentStepId")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresCycle")
                        .HasColumnType("boolean");

                    b.Property<int>("StepCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentStepId");

                    b.ToTable("DiscipleSteps");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.StepCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("DiscipleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiscipleStepId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("LastUpdated")
                        .HasColumnType("date");

                    b.Property<string>("LeaderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StepCycleId")
                        .HasColumnType("integer");

                    b.Property<int>("StepStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscipleId");

                    b.HasIndex("DiscipleStepId");

                    b.HasIndex("LeaderId");

                    b.HasIndex("StepCycleId");

                    b.ToTable("StepCompletions");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.StepCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscipleStepId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EnrollmentDeadline")
                        .HasColumnType("date");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<int>("MinAttendanceRequired")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DiscipleStepId");

                    b.HasIndex("DiscipleStepId", "IsOpen");

                    b.ToTable("StepCycles");
                });

            modelBuilder.Entity("JMMinistry.Domain.Discipleship.DiscipleshipNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiscipleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeaderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscipleId");

                    b.HasIndex("LeaderId");

                    b.ToTable("DiscipleshipNotes");
                });

            modelBuilder.Entity("JMMinistry.Domain.Discipleship.DiscipleshipNoteEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NoteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("NoteId");

                    b.ToTable("DiscipleshipNoteEntries");
                });

            modelBuilder.Entity("JMMinistry.Domain.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("JMMinistry.Domain.Location.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("JMMinistry.Domain.Location.Locality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Localities", (string)null);
                });

            modelBuilder.Entity("JMMinistry.Domain.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsRecurrent")
                        .HasColumnType("boolean");

                    b.Property<int>("MeetingType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("JMMinistry.Domain.MeetingAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MeetingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("MeetingAttendances");
                });

            modelBuilder.Entity("JMMinistry.Domain.PersonalInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CellEnrollmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CellId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<int?>("EducationalLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locality")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Occupation")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SpouseId")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SpouseId")
                        .IsUnique()
                        .HasFilter("\"SpouseId\" IS NOT NULL");

                    b.HasIndex("Name", "LastName");

                    b.ToTable("PersonalInfo", (string)null);
                });

            modelBuilder.Entity("JMMinistry.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("MeetingAttendancePersonalInfo", b =>
                {
                    b.Property<string>("AttendeesId")
                        .HasColumnType("text");

                    b.Property<int>("MeetingAttendancesId")
                        .HasColumnType("integer");

                    b.HasKey("AttendeesId", "MeetingAttendancesId");

                    b.HasIndex("MeetingAttendancesId");

                    b.ToTable("MeetingAttendancePersonalInfo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JMMinistry.Domain.PersonalInfoRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.HasIndex("RoleId");

                    b.HasDiscriminator().HasValue("PersonalInfoRole");
                });

            modelBuilder.Entity("CellAttendancePersonalInfo", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", null)
                        .WithMany()
                        .HasForeignKey("AttendeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.CellAttendance", null)
                        .WithMany()
                        .HasForeignKey("CellAttendancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CellPersonalInfo", b =>
                {
                    b.HasOne("JMMinistry.Domain.Cell", null)
                        .WithMany()
                        .HasForeignKey("CellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.PersonalInfo", null)
                        .WithMany()
                        .HasForeignKey("LeadersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscipleStepDiscipleStep", b =>
                {
                    b.HasOne("JMMinistry.Domain.DiscipleJourney.DiscipleStep", null)
                        .WithMany()
                        .HasForeignKey("DiscipleStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.DiscipleJourney.DiscipleStep", null)
                        .WithMany()
                        .HasForeignKey("DiscipleStepRequirementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JMMinistry.Domain.Cell", b =>
                {
                    b.HasOne("JMMinistry.Domain.Location.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("JMMinistry.Domain.Location.Locality", "Locality")
                        .WithMany()
                        .HasForeignKey("LocalityId");

                    b.Navigation("City");

                    b.Navigation("Locality");
                });

            modelBuilder.Entity("JMMinistry.Domain.CellAttendance", b =>
                {
                    b.HasOne("JMMinistry.Domain.Cell", "Cell")
                        .WithMany()
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cell");
                });

            modelBuilder.Entity("JMMinistry.Domain.ConventionAttendee", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Attendee")
                        .WithMany("Conventions")
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.Convention", "Convention")
                        .WithMany()
                        .HasForeignKey("ConventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.PersonalInfo", "InvitedBy")
                        .WithMany("ConventionInvites")
                        .HasForeignKey("InvitedById");

                    b.Navigation("Attendee");

                    b.Navigation("Convention");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.CycleAttendance", b =>
                {
                    b.HasOne("JMMinistry.Domain.DiscipleJourney.CycleSession", "CycleSession")
                        .WithMany("Attendances")
                        .HasForeignKey("CycleSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Disciple")
                        .WithMany()
                        .HasForeignKey("DiscipleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CycleSession");

                    b.Navigation("Disciple");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.CycleEnrollment", b =>
                {
                    b.HasOne("JMMinistry.Domain.DiscipleJourney.CycleStaff", "CycleStaff")
                        .WithMany("Enrollments")
                        .HasForeignKey("CycleStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Disciple")
                        .WithMany()
                        .HasForeignKey("DiscipleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.DiscipleJourney.StepCycle", "StepCycle")
                        .WithMany("Enrollments")
                        .HasForeignKey("StepCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CycleStaff");

                    b.Navigation("Disciple");

                    b.Navigation("StepCycle");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.CycleSession", b =>
                {
                    b.HasOne("JMMinistry.Domain.DiscipleJourney.StepCycle", "StepCycle")
                        .WithMany("Sessions")
                        .HasForeignKey("StepCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StepCycle");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.CycleStaff", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.DiscipleJourney.StepCycle", "StepCycle")
                        .WithMany("Staff")
                        .HasForeignKey("StepCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("StepCycle");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.DiscipleStep", b =>
                {
                    b.HasOne("JMMinistry.Domain.DiscipleJourney.DiscipleStep", "ParentStep")
                        .WithMany("SubSteps")
                        .HasForeignKey("ParentStepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentStep");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.StepCompletion", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Disciple")
                        .WithMany("StepCompletions")
                        .HasForeignKey("DiscipleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.DiscipleJourney.DiscipleStep", "DiscipleStep")
                        .WithMany()
                        .HasForeignKey("DiscipleStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Leader")
                        .WithMany("SupervisedStepCompletions")
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.DiscipleJourney.StepCycle", "StepCycle")
                        .WithMany()
                        .HasForeignKey("StepCycleId");

                    b.Navigation("Disciple");

                    b.Navigation("DiscipleStep");

                    b.Navigation("Leader");

                    b.Navigation("StepCycle");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.StepCycle", b =>
                {
                    b.HasOne("JMMinistry.Domain.DiscipleJourney.DiscipleStep", "DiscipleStep")
                        .WithMany("Cycles")
                        .HasForeignKey("DiscipleStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscipleStep");
                });

            modelBuilder.Entity("JMMinistry.Domain.Discipleship.DiscipleshipNote", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Disciple")
                        .WithMany()
                        .HasForeignKey("DiscipleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciple");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("JMMinistry.Domain.Discipleship.DiscipleshipNoteEntry", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.Discipleship.DiscipleshipNote", "Note")
                        .WithMany("Entries")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("JMMinistry.Domain.Location.Locality", b =>
                {
                    b.HasOne("JMMinistry.Domain.Location.City", null)
                        .WithMany("Localities")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("JMMinistry.Domain.MeetingAttendance", b =>
                {
                    b.HasOne("JMMinistry.Domain.Meeting", "Meeting")
                        .WithMany("MeetingAttendances")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("JMMinistry.Domain.PersonalInfo", b =>
                {
                    b.HasOne("JMMinistry.Domain.Cell", "Cell")
                        .WithMany("Disciples")
                        .HasForeignKey("CellId");

                    b.HasOne("JMMinistry.Domain.PersonalInfo", "Spouse")
                        .WithOne()
                        .HasForeignKey("JMMinistry.Domain.PersonalInfo", "SpouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cell");

                    b.Navigation("Spouse");
                });

            modelBuilder.Entity("MeetingAttendancePersonalInfo", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", null)
                        .WithMany()
                        .HasForeignKey("AttendeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.MeetingAttendance", null)
                        .WithMany()
                        .HasForeignKey("MeetingAttendancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("JMMinistry.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JMMinistry.Domain.PersonalInfo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JMMinistry.Domain.PersonalInfoRole", b =>
                {
                    b.HasOne("JMMinistry.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JMMinistry.Domain.PersonalInfo", "PersonalInfo")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalInfo");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JMMinistry.Domain.Cell", b =>
                {
                    b.Navigation("Disciples");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.CycleSession", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.CycleStaff", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.DiscipleStep", b =>
                {
                    b.Navigation("Cycles");

                    b.Navigation("SubSteps");
                });

            modelBuilder.Entity("JMMinistry.Domain.DiscipleJourney.StepCycle", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Sessions");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("JMMinistry.Domain.Discipleship.DiscipleshipNote", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("JMMinistry.Domain.Location.City", b =>
                {
                    b.Navigation("Localities");
                });

            modelBuilder.Entity("JMMinistry.Domain.Meeting", b =>
                {
                    b.Navigation("MeetingAttendances");
                });

            modelBuilder.Entity("JMMinistry.Domain.PersonalInfo", b =>
                {
                    b.Navigation("ConventionInvites");

                    b.Navigation("Conventions");

                    b.Navigation("StepCompletions");

                    b.Navigation("SupervisedStepCompletions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("JMMinistry.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
