<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6a94bb88-1717-4f96-b40c-7ba3b6302f07</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <LangVersion>13</LangVersion>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Pages\Schools.razor" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.FluentValidation" Version="2.2.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Fluxor.Blazor.Web" Version="6.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.2" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.8.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.2" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" Version="8.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="..\.dockerignore" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\LogIn.razor" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Layout\EmptyLayout.razor" />
    <_ContentIncludedByDefault Remove="Pages\LogIn.razor" />
    <_ContentIncludedByDefault Remove="Pages\Schools.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JMMinistry.Common\JMMinistry.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Layout\EmptyLayout.razor" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Schools.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
