worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {
    include mime.types;

    limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;

    types {
        application/wasm wasm;
    }

    server {
        listen 80;

        # Set the location for Nginx to serve the files
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html =404;
        }
    }
}
